# Generated by Django 5.1.1 on 2024-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.CharField(max_length=222)),
                ('date_bith', models.CharField(max_length=222)),
                ('adress', models.CharField(max_length=222)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=222)),
            ],
        ),
    ]
