# Generated by Django 5.1.1 on 2024-10-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_index_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=222)),
                ('name', models.CharField(max_length=222)),
                ('university', models.CharField(max_length=222)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=222)),
                ('position', models.CharField(max_length=222)),
                ('university', models.CharField(max_length=222)),
                ('body', models.TextField()),
            ],
        ),
    ]
