# Generated by Django 5.1.1 on 2024-10-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='last_month',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='last_week',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
    ]
