# Generated by Django 5.1.1 on 2024-10-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_skill_last_month_skill_last_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dasturlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photoshop', models.CharField(max_length=222)),
                ('jQuery', models.CharField(max_length=222)),
                ('HTML5', models.CharField(max_length=222)),
                ('CSS3', models.CharField(max_length=222)),
                ('WordPress', models.CharField(max_length=222)),
                ('SEO', models.CharField(max_length=222)),
            ],
        ),
    ]
