# Generated by Django 5.1.1 on 2024-10-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_dasturlash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('body', models.CharField(max_length=222)),
                ('description', models.TextField()),
                ('yil', models.CharField(max_length=222)),
            ],
        ),
    ]
