# Generated by Django 5.1.1 on 2024-10-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('body', models.CharField(max_length=221)),
                ('image', models.ImageField(upload_to='blog/')),
            ],
        ),
    ]
