# Generated by Django 5.1.1 on 2024-10-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('title2', models.CharField(max_length=222)),
                ('name', models.CharField(max_length=222)),
                ('body1', models.TextField()),
                ('body2', models.TextField()),
                ('body3', models.TextField()),
                ('body4', models.TextField()),
                ('image', models.ImageField(upload_to='single-image/')),
            ],
        ),
    ]
