# Generated by Django 5.1.1 on 2024-10-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='image2',
            field=models.ImageField(default=1, upload_to='single-image2/'),
            preserve_default=False,
        ),
    ]
